### PR TITLE
Fixed csrfToken

### PR DESCRIPTION
**Pull request by srahnama**

### CODE REVIEW

**Comment by tuxity** [comment]
Thanks for you contribution!

Can you explain why? Just tested it few minutes ago and it works well like this.

**Comment by srahnama** [comment]
> Thanks for you contribution!
> 
> Can you explain why? Just tested the current version few minutes ago and it works well without this change.

Hi, it is not working for me, I changed this and it worked, 
The response from self.s.get(self.url) should contain cookies, or at least one named csrftoken. However, the response from GET('https://www.instagram.com') returns no cookies sometimes, not sure why. This cookie is necessary when setting headers later on... That may be sudden changes about cookie policy when resquesting the whole domain instagram.com

**Comment by tuxity** [comment]
Ok, let me double check this before merging. But it sounds good

**Comment by tuxity** [comment]
Everything seems to work well without this change, so I’m gonna close this PR for now. Thanks again

**Pull request closed without merging**
